version: "3.8"
services:
  prometheus_runtime:
    image: "prom/prometheus:latest"
      #ports:
      #- "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=http://localhost/prom
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./consoles/:/etc/prometheus/consoles/
    restart: always
    networks:
      junknet:
        #        aliases:
        #          - prom.internal.local
  otel-collector:
    image: "otel/opentelemetry-collector-contrib:latest"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - /:/hostfs
    restart: always
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      junknet:
  frontend:
    image: "caddy:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./www:/usr/share/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: always
    networks:
      junknet:

networks:
  junknet:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  back_caddy_data:
  back_caddy_config: