receivers:
  hostmetrics:
    collection_interval: 30s
    root_path: /hostfs
    scrapers:
      cpu:
        metrics:
          system.cpu.frequency:
            enabled: true
          system.cpu.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      processes:

  hostmetrics/disk:
    root_path: /hostfs
    collection_interval: 1m
    scrapers:
      disk:
      filesystem:
processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"


service:
  pipelines:
    metrics:
      receivers: [hostmetrics, hostmetrics/disk]
      processors:
      exporters: [prometheus]